[project]
name = "Diffusion_K"
version = "0.1.0"
author = "Korarei"
requires-aviutl2 = "2003800"

[build]
[[build.scripts]]
id = "effect"
prefix = "@"
suffix = ".anm2"
variables = { SOURCE = "./src" }
include_directories = ["${SOURCE}/shaders"]
sources = [
    { file = "${SOURCE}/gaussian_blur.lua", LABEL = "ぼかし" },
    { file = "${SOURCE}/channel_blur.lua", LABEL = "ぼかし" },
    { file = "${SOURCE}/orton.lua", LABEL = "光効果" },
    { file = "${SOURCE}/dissolve.lua", LABEL = "加工" },
    { file = "${SOURCE}/scatter.lua", LABEL = "加工" },
    { file = "${SOURCE}/noise.lua", LABEL = "加工" },
    { file = "${SOURCE}/noise_hsla.lua", LABEL = "加工" },
]

[release]
[release.package]
information = "${PROJECT_NAME} v${PROJECT_VERSION} by ${PROJECT_AUTHOR}"
license = "MIT"
website = "https://github.com/korarei/AviUtl2_Diffusion_K_Script"
report-issue = "https://github.com/korarei/AviUtl2_Diffusion_K_Script/issues"
summary = "オートン効果スクリプト"
description = """
以下の機能が追加される
- 光効果 -> Orton: オートン効果
- ぼかし -> GaussianBlur: ガウシアンブラー
- ぼかし -> ChannelBlur: チャンネル別ガウシアンブラー
- 加工 -> Dissolve: ディザ合成
- 加工 -> Scatter: ピクセル拡散
- 加工 -> Noise: ノイズ
- 加工 -> Noise(HSLA): HSLAノイズ
"""

[[release.contents.extensions]]
directory = "Script/${PROJECT_NAME}"
files = ["script:effect"]

[[release.contents.documents]]
directory = "Script/${PROJECT_NAME}"
files = ["./*.md", "./LICENSE"]
